- name: Sync TimeZone Date NTP 
  hosts: ec2
  tasks: 
    - name: Set timezone
      timezone:
        name: Asia/Bangkok

    - name: Check ntp is started and Set enabled on boot.
      service: name=ntp state=started enabled=yes