- name: Disabled Auto update and upgrade
  hosts: ec2
  tasks:  
    - name: Disable auto update
      replace:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: 'APT::Periodic::Update-Package-Lists "1";'
        replace: 'APT::Periodic::Update-Package-Lists "0";'

    - name: Disable auto unattend upgrade
      replace:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: 'APT::Periodic::Unattended-Upgrade "1";;'
        replace: 'APT::Periodic::Unattended-Upgrade "0";'